openapi: 3.1.0

info:
  title: RAP API
  version: "v1"

paths:
  /backend/status/:
    get:
      security:
        - bearerAuth: []
      description: |
        Get the status (flags) for all backends.
      tags:
        - backends
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  flags:
                    type: object
                    additionalProperties:
                      type: object
                      additionalProperties:
                        type: object
                        properties:
                          v:
                            type: string
                            nullable: true
                            description: flag value
                          ts:
                            type: string
                            description: timestamp
              examples:
                ex1:
                  value:
                    flags:
                      test:
                        paused:
                          v: on
                          ts: 2025-07-29T16:12:28.216609Z
        401:
          $ref: "#/components/responses/401Unauthorized"

  /rap/cancel/:
      post:
        security:
          - bearerAuth: []
        description: |
          Cancel one or more actions.
        tags:
        - rap_operations
        requestBody:
          required: true
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/cancelRequestBody"
              examples:
                ex1:
                  value:
                    backend: test
                    job_request_id: a1b2c3d4e5f6g7h8
                    actions: ["foo"]
        responses:
          200:
            description: OK
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    success:
                      type: string
                    details:
                      type: string
                examples:
                  ex1:
                    value:
                      success: ok
                      details: 2 actions cancelled
          400:
            description: Bad response
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    error:
                      type: string
                    details:
                      type: string
                examples:
                  ex1:
                    value:
                      description: Missing job_request_id
                      error: Validation error
                      details": "Invalid request body received: 'job_request_id' is a required property"
          401:
            $ref: "#/components/responses/401Unauthorized"
          403:
            $ref: "#/components/responses/403NotAllowedBackend"
          404:
            $ref: "#/components/responses/404UnknownBackend"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: token

  schemas:
    cancelRequestBody:
      # Can be referenced as '#/components/schemas/cancelRequestBody'
      type: object
      required:
        - backend
        - job_request_id
        - actions
      properties:
        backend:
          type: string
          examples:
            - test
            - tpp
            - emis
        job_request_id:
          type: string
          pattern: "^[a-z0-9]{16}$"
        actions:
          type: array
          minItems: 1
          items:
            type: string

  responses:
    401Unauthorized:
      # Can be referenced as '#/components/responses/401Unauthorized'
      description: Unauthorized
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
              details:
                type: string
          examples:
            ex1:
              value:
                error: "Unauthorized"
                details: "Invalid token"
    403NotAllowedBackend:
      # Can be referenced as '#/components/responses/404UnknownBackend'
      description: unknown backend
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
              details:
                type: string
          examples:
            ex1:
              value:
                error: "Not allowed"
                details: "Not allowed for backend 'foo'"
    404UnknownBackend:
      # Can be referenced as '#/components/responses/404UnknownBackend'
      description: unknown backend
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
              details:
                type: string
          examples:
            ex1:
              value:
                error: "Not found"
                details: "Backend 'foo' not found"

security:
  - bearerAuth: []

tags:
  - name: backends
    x-displayName: Backend status
    description: Endpoints that provide information about backend status.
  - name: rap_operations
    x-displayName: RAP Operations
    description: Endpoints that perform operations on RAPs
