openapi: 3.1.0

info:
  title: RAP API
  description: OpenSAFELY Reproducible Analytic Pipeline (RAP) API
  version: "v1"

servers:
- url: /controller/v1/

paths:
  /backend/status/:
    get:
      security:
        - bearerAuth: []
      description: |
        Get the status (flags) for all backends.
      tags:
        - backends
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                required:
                  - backends
                properties:
                  backends:
                    type: array
                    items:
                      type: object
                      required:
                       - name
                      properties:
                        name:
                         type: string
                         description: Name of backend


              examples:
                ex1:
                  value:
                    backends:
                      - name: test

        401:
          $ref: "#/components/responses/401Unauthorized"

  /rap/create/:
      post:
        security:
          - bearerAuth: []
        description: |
          Create a RAP with one or more actions
        tags:
        - rap_operations
        requestBody:
          required: true
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/createRequestBody"
              examples:
                example1:
                  value:
                    backend: test
                    rap_id: a1b2c3d4e5f6g7h8
                    workspace: test-study
                    repo_url: https://github.com/opensafely/test-study
                    branch: main
                    commit: 07d5f283bb66f52a49933b016cf8dc144cfc7180
                    database_name: default
                    requested_actions:
                     - action1
                    codelists_ok: true
                    force_run_dependencies: false
                    created_by: test_user
                    project: test-project
                    orgs:
                     - opensafely
        responses:
          200:
            description: OK
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    success:
                      type: string
                    details:
                      type: string
                    rap_id:
                      type: string
                examples:
                  success:
                    description: success
                    value:
                      success: ok
                      details: Received create request for RAP ID a1b2c3d4e5f6g7h8
                      rap_id: a1b2c3d4e5f6g7h8
          400:
            description: Bad response
            content:
              application/json:
                schema:
                  type: object
                  required:
                   - error
                   - details
                  properties:
                    error:
                      type: string
                    details:
                      type: string
                    rap_id:
                      description: rap_id parameter
                      type: string
                examples:
                  validation_error:
                    description: Missing rap_id
                    value:
                      error: Validation error
                      details: "Invalid request body received: 'rap_id' is a required property"
          401:
            $ref: "#/components/responses/401Unauthorized"
          403:
            $ref: "#/components/responses/403NotAllowedBackend"

  /rap/cancel/:
      post:
        security:
          - bearerAuth: []
        description: |
          Cancel one or more actions.
        tags:
        - rap_operations
        requestBody:
          required: true
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/cancelRequestBody"
              examples:
                example1:
                  value:
                    rap_id: a1b2c3d4e5f6g7h8
                    actions: ["action1"]
                example2:
                  value:
                    rap_id: abcdefgh12345678
                    actions: ["action2", "action3"]
        responses:
          200:
            description: OK
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    success:
                      type: string
                    details:
                      type: string
                    count:
                      description: Number of actions cancelled
                      type: integer
                examples:
                  success:
                    description: 2 actions successfully cancelled
                    value:
                      success: ok
                      details: 2 actions cancelled
                      count: 2
          400:
            description: Bad response
            content:
              application/json:
                schema:
                  type: object
                  required:
                   - error
                   - details
                  properties:
                    error:
                      type: string
                    details:
                      type: string
                    rap_id:
                      description: rap_id parameter
                      type: string
                    not_found:
                      description: actions requested for cancellation that do not exist for the requested rap_id
                      type: array
                      items:
                        type: string
                examples:
                  validation_error:
                    description: Missing rap_id
                    value:
                      error: Validation error
                      details: "Invalid request body received: 'rap_id' is a required property"
                  data_error1:
                    description: No jobs found matching rap_id
                    value:
                      error: jobs not found
                      details: No jobs found for rap_id abcdefgh12345678
                      rap_id: abcdefgh12345678
                  data_error2:
                    description: Jobs matching requested cancel actions are not found
                    value:
                      error: Jobs not found
                      details: "Jobs matching requested cancelled actions could not be found: action1,action2"
                      rap_id: abcdefgh12345678
                      not_found: ["action1", "action2"]
          401:
            $ref: "#/components/responses/401Unauthorized"
          403:
            $ref: "#/components/responses/403NotAllowedBackend"

  /rap/status/:
      post:
        security:
          - bearerAuth: []
        description: |
          Get the status of RAPs
        tags:
        - rap_operations
        requestBody:
          required: true
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/statusRequestBody"
              examples:
                example1:
                  value:
                    rap_ids: [
                      a1b2c3d4e5f6g7h8
                    ]
                example2:
                  value:
                    rap_ids: [
                      abcdefgh12345678
                    ]
        responses:
          200:
            description: OK
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    rap_statuses:
                      type: array
                      items:
                        type: object
                        properties:
                          rap_id:
                            type: string
                          status:
                            type: string
                          details:
                            type: string
                examples:
                  success:
                    description: success
                    value:
                      rap_statuses:
                        [{
                          rap_id: a1b2c3d4e5f6g7h8,
                          status: ok,
                          details: running,
                        }]
          400:
            description: Bad response
            content:
              application/json:
                schema:
                  type: object
                  required:
                   - error
                   - details
                  properties:
                    error:
                      type: string
                    details:
                      type: string
                examples:
                  validation_error:
                    description: Missing rap_ids
                    value:
                      error: Validation error
                      details: "Invalid request body received: 'rap_ids' is a required property"
          401:
            $ref: "#/components/responses/401Unauthorized"
          403:
            $ref: "#/components/responses/403NotAllowedBackend"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: token
  schemas:
    createRequestBody:
      # Can be referenced as '#/components/schemas/createRequestBody'
      type: object
      required:
        - backend
        - rap_id
        - workspace
        - repo_url
        - branch
        - commit
        - database_name
        - requested_actions
        - codelists_ok
        - force_run_dependencies
        - created_by
        - project
        - orgs
      properties:
        backend:
          description: The backend this RAP should run on
          type: string
        rap_id:
          description: A unique identifier for this RAP
          type: string
          pattern: '^[a-z0-9]{16}$'
        workspace:
          type: string
          pattern: '[a-zA-Z0-9_-]+'
        repo_url:
          type: string
        branch:
          type: string
        commit:
          description: commit sha
          type: string
          pattern: '^[0-9a-f]{40}$'
        database_name:
          type: string
          enum:
            - default
            - include_t1oo
        requested_actions:
          description: |
            The explicitly requested actions to run as part of this RAP.
            Note that other actions may be run if they are unmet dependencies of the
            requested actions.
          type: array
          minItems: 1
          items:
            type: string
        codelists_ok:
          type: boolean
        force_run_dependencies:
          type: boolean
        created_by:
          description: Username
          type: string
        project:
          type: string
        orgs:
          type: array
          items:
            type: string
    cancelRequestBody:
      # Can be referenced as '#/components/schemas/cancelRequestBody'
      type: object
      required:
        - rap_id
        - actions
      properties:
        rap_id:
          type: string
          pattern: '^[a-z0-9]{16}$'
        actions:
          type: array
          minItems: 1
          items:
            type: string
    statusRequestBody:
      # Can be referenced as '#/components/schemas/statusRequestBody'
      type: object
      required:
        - rap_ids
      properties:
        rap_ids:
          type: array
          items:
            type: string
            pattern: '^[a-z0-9]{16}$'

  responses:
    401Unauthorized:
      # Can be referenced as '#/components/responses/401Unauthorized'
      description: Unauthorized
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
              details:
                type: string
          examples:
            invalid_token:
              value:
                error: "Unauthorized"
                details: "Invalid token"
    403NotAllowedBackend:
      # Can be referenced as '#/components/responses/404UnknownBackend'
      description: unknown backend
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
              details:
                type: string
          examples:
            not_allowed_for_backend:
              value:
                error: "Not allowed"
                details: "Not allowed for backend 'foo'"

security:
  - bearerAuth: []

tags:
  - name: backends
    x-displayName: Backend status
    description: Endpoints that provide information about backend status.
  - name: rap_operations
    x-displayName: RAP Operations
    description: Endpoints that perform operations on RAPs
