openapi: 3.1.0

info:
  title: RAP API OpenAPI Description
  version: "v1"

paths:
  /{backend}/backend/status/:
    get:
      security:
        - bearerAuth: []
      description: |
        Get the status (flags) for a specific backend.
      parameters:
      - $ref: "#/components/parameters/backendParam"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  flags:
                    type: object
                    additionalProperties:
                      type: object
                      properties:
                        v:
                          type: string
                          nullable: true
                          description: flag value
                        ts:
                          type: string
                          description: timestamp
              examples:
                ex1:
                  value:
                    flags:
                      paused:
                        v: on
                        ts: 2025-07-29T16:12:28.216609Z
        401:
          $ref: "#/components/responses/401Unauthorized"
        404:
          $ref: "#/components/responses/404UnknownBackend"

  /backend/status/:
    get:
      security:
        - bearerAuth: []
      description: |
        Get the status (flags) for all backends.
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  flags:
                    type: object
                    additionalProperties:
                      type: object
                      additionalProperties:
                        type: object
                        properties:
                          v:
                            type: string
                            nullable: true
                            description: flag value
                          ts:
                            type: string
                            description: timestamp
              examples:
                ex1:
                  value:
                    flags:
                      test:
                        paused:
                          v: on
                          ts: 2025-07-29T16:12:28.216609Z
        401:
          $ref: "#/components/responses/401Unauthorized"


components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: token

  parameters:
    backendParam:
      name: backend
      in: path
      description: name of backend
      required: true
      schema:
        type: string
        enum:
        - test
        - tpp
        - emis
        example: test

  responses:
    401Unauthorized:
      # Can be referenced as '#/components/responses/401Unauthorized'
      description: Unauthorized
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
              details:
                type: string
          examples:
            ex1:
              value:
                error: "Unauthorized"
                details: "Invalid token"
    404UnknownBackend:
      # Can be referenced as '#/components/responses/404UnknownBackend'
      description: unknown backend
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
              details:
                type: string
          examples:
            ex1:
              value:
                error: "Not found"
                details: "Backend 'foo' not found"

security:
  - bearerAuth: []
