generation.max-examples = 100
headers = { Authorization = "rap_token" }

[output.sanitization]
enabled = false

# Turn off positive_data_acceptance checks for endpoints with custom
# validation for validly shaped data. e.g. if we try to cancel a job request id with
# actions that don't exist, we'll get an unexpected (as far as schemathesis is concerned)
# 400 error
# See suggestion from schemathesis author to do just this: https://github.com/schemathesis/schemathesis/issues/2710#issuecomment-2622411255
# We expect the validation to be covered in unit tests, so we just ignore for api spec tests
# for now.

[[operations]]
include-name = "POST /rap/cancel/"
checks.positive_data_acceptance.enabled = false

[[operations]]
include-name = "POST /rap/create/"
checks.positive_data_acceptance.enabled = false
