name: Tests

on:
  pull_request:

permissions:
  contents: read

jobs:

  check:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: opensafely-core/setup-action@d9171097dd0d37bdb7bed58f701eb03ff317ed17 # v1
        with:
          install-just: true
          install-uv: true
          cache: uv
      - name: Check formatting, linting and import sorting
        run: just check

  test-job:
    runs-on: ubuntu-24.04
    name: Run test suite
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
         persist-credentials: false
      - uses: opensafely-core/setup-action@d9171097dd0d37bdb7bed58f701eb03ff317ed17 # v1
        with:
          install-just: true
          install-uv: true
          cache: uv
      - name: Run tests
        run: |
          just devenv
          just test -vvv

  test-docker:
    runs-on: ubuntu-24.04
    name: Test docker image (${{ matrix.docker-backend }})
    strategy:
      fail-fast: false
      matrix:
        docker-backend: [github-native, docker.io]
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Set up Just
        uses: extractions/setup-just@53165ef7e734c5c07cb06b3c8e7b647c5aa16db3

      - name: Swap runner's Docker for docker.io (to match the docker used in the backend)
        if: matrix.docker-backend == 'docker.io'
        run: |
          sudo systemctl stop docker
          sudo apt-get remove -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo systemctl start docker

      - name: Confirm docker server version
        run: docker version

      - name: Build dev image
        run: just docker/build dev

      - name: Run tests in docker-image
        run: just docker/test

      - name: Build production image
        run: just docker/build prod

      - name: Run basic multi-container integration test
        run: just docker/functional-test

      - name: Save image as artifact
        # We only want to persist a single image here so we need to pick a backend. The
        # image contents should be very close to identical so it's a fairly arbitrary
        # choice. But the docker.io backend is slightly newer and matches what we
        # currently have in TPP so it makes sense to use that.
        if: success() && matrix.docker-backend == 'docker.io'
        uses: ./.github/actions/save-image-as-artifact
        with:
          image-name: job-runner
          artifact-name: image

  required-checks:
    if: always()

    needs:
      - check
      - test-job
      - test-docker

    runs-on: ubuntu-24.04

    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@b5b5b37504aa4183270bd3d855c52a67f212be35 # v1.3.0
        with:
          jobs: ${{ toJSON(needs) }}
