name: Update python dependencies

on:
  workflow_dispatch:
  schedule:
    - cron:  "0 4 * * WED"

permissions:
  contents: read

jobs:
  update-dependencies:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      with:
        persist-credentials: false
    - uses: opensafely-core/setup-action@93841f27c28c75bf85b1a0a915e2391a06c6c8a6 # v1
      with:
        install-just: true
        install-uv: true
        cache: uv

    - uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3
      id: generate-token
      with:
        app-id: 1031449  # opensafely-core Create PR app
        private-key: ${{ secrets.CREATE_PR_APP_PRIVATE_KEY }}

    - uses: bennettoxford/update-dependencies-action@b77a22bcfe1d06020d908e64c9828fe944da3a5e # v1
      id: update
      with:
        token: ${{ steps.generate-token.outputs.token }}

    - name: Notify slack of PR
      if: ${{ steps.update.outputs.pull-request-operation != 'none' }}
      uses: slackapi/slack-github-action@03ea5433c137af7c0495bc0cad1af10403fc800c  # v3.0.2
      with:
        method: chat.postMessage
        token: ${{ secrets.BENNETTBOT_SLACK_BOT_TOKEN }}
        payload: |
          channel: "C080S7W2ZPX"
          text: "Update dependencies\n${{ steps.update.outputs.pull-request-url }}"
