---
name: Check uvmirror

permissions:
  contents: read

on:
  push:
  workflow_dispatch:

jobs:
  check-uvmirror:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          persist-credentials: false
      - uses: opensafely-core/setup-action@93841f27c28c75bf85b1a0a915e2391a06c6c8a6 # v1
        with:
          install-just: true
          install-uv: true
          cache: uv

      - name: Ensure requirements.uvmirror.txt is consistent with uv.lock
        run: just uvmirror && git diff -s --exit-code
